---

- name: Install fail2ban Package
  yum:
    name: fail2ban
    state: installed

- name: Configure jail
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify:
    - bounce fail2ban service

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: true
