---

# Right now all I wanna do is setup DNS, but will have some other network
# stuff to configure
- name: Configure resolv.conf with name servers
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
