---

- name: Install openssh Package
  yum:
    name: openssh
    state: present

- name: SSHD config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify:
    - bounce sshd service

- name: SSH config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'
  notify:
    - bounce sshd service

- name: Ensure sshd is running
  service:
    name: sshd
    state: started
    enabled: true
